### ISSUE TITLE
Replication tries to access workspace with wrong URL

### ISSUE THREAD

**Issue by fago** [relaxedws/couchdb-replicator#10] opened 2018-08-16 16:40 UTC
While working on  test-coverage for drunomics/contentpool-client I had the issue that replication suddenly was not working any more. I always got in the log:
Doctrine\CouchDB\HTTP\HTTPException: HTTP Error with status 404 occurred while requesting /. Error: not_found Workspace does not exist.

Debugging showed that this wrong request was made:

`GET /relaxed/relaxed HTTP/1.1 Authorization: Basic **** Connection: Keep-Alive, Keep-Alive Content-Type: application/json Host: contentpool-project.localdev.space Php-Auth-Pw: changeme Php-Auth-User: replicator X-Php-Ob-Level: 1 in Doctrine\CouchDB\HTTP\HTTPException::fromResponse() (line 68 of /srv/default/vcs/satellite-project/vendor/relaxedws/couchdb/lib/Doctrine/CouchDB/HTTP/HTTPException.php).`

Note the **relaxed/relaxed** - there should be only one relaxed in the URL. This was not happening before and after some time-consuming trial and error I figured it's coming from the latest update of relaxedws/couchdb and relaxedws/replicator.

Those previsous versions still work for me and do not have this bug:
$ composer require relaxedws/couchdb:dev-master#648d6ef
$ composer require relaxedws/replicator:dev-master#3b04a9f

**Comment by jeqq** [comment] 2018-08-17 09:21
@fago Do you have Redirect module installed on the projects? We found on some of our projects that this issue has been cause by redirects done by Redirect module. When you have a `/` at the end of the link. Redirect module has a setting that makes links like `/relaxed/` to redirect to `/relaxed`. The problem is not in the the change we added in the latest commits, but somewhere else in the library (relaxedws/couchdb), it doesn't handle correctly redirects. As a workaround we disabled that setting for Redirect, there is a checkbox, or `$config['redirect.settings']['route_normalizer_enabled'] = FALSE;`.

For long term we think about using Guzzle instead of relaxedws/couchdb.

**Comment by fago** [comment] 2018-08-20 11:16
> The problem is not in the the change we added in the latest commits, but somewhere else in the library (relaxedws/couchdb), it doesn't handle correctly redirects.

Interesting. Yeah, we have redirect on the contentpool (= "server"), so this is probably the cause. Interestingly it does not pop up with the mentioned versions. Anyway, I'll try this.

**Comment by akhomy** [comment] 2018-11-06 10:29
Hi, @fago, @jeqq. As it was mentioned here and in https://www.drupal.org/project/relaxed/issues/3007313
there is a problem, as good workaround, you can test patch from above link. 
@jeqq, IMHO, I think you can add this to the module code and use it. I've tested and it works fine, but I think we need to have proof from you or another person that has tested patch.
Or I can create PR if you prefer such way workflow.

Also, I think, that disabling redirect option isn't a good way.

Let me know what do you think.

**Comment by jhedstrom** [comment] 2019-06-05 20:46
The patch mentioned above seems better than completely disabling all `/foo/` style redirects, since it only targets the relaxed routes. It seems to have resolved the issue in my testing.

**Comment by jeqq** [comment] 2019-06-10 09:00
Fixed in https://www.drupal.org/project/relaxed/issues/3007313.

**Closed as completed by jeqq** 2019-06-10 09:00 UTC
